<?php
/**
 * Exact paths for declaration-only legacy classes deferred by core bootstrap.
 */

defined( 'ABSPATH' ) || exit;

return [
    'Directorist\\Contracts\\PaymentInterface'             => ATBDP_INC_DIR . 'contracts/payment-interface.php',
    'Directorist\\DBModels\\Order'                         => ATBDP_INC_DIR . 'db-models/order.php',
    'Directorist\\DBModels\\Payment'                       => ATBDP_INC_DIR . 'db-models/payment.php',
    'Directorist\\DBModels\\Post'                          => ATBDP_INC_DIR . 'db-models/post.php',
    'Directorist\\DBModels\\Refund'                        => ATBDP_INC_DIR . 'db-models/refund.php',
    'Directorist\\DBModels\\Subscription'                  => ATBDP_INC_DIR . 'db-models/subscription.php',
    'Directorist\\DBModels\\User'                          => ATBDP_INC_DIR . 'db-models/user.php',
    'Directorist\\DTO\\Order\\DTO'                         => ATBDP_INC_DIR . 'dto/order/dto.php',
    'Directorist\\DTO\\Order\\Read'                        => ATBDP_INC_DIR . 'dto/order/read.php',
    'Directorist\\DTO\\Payment\\DTO'                       => ATBDP_INC_DIR . 'dto/payment/dto.php',
    'Directorist\\DTO\\Refund\\DTO'                        => ATBDP_INC_DIR . 'dto/refund/dto.php',
    'Directorist\\DTO\\Refund\\Read'                       => ATBDP_INC_DIR . 'dto/refund/read.php',
    'Directorist\\DTO\\Subscription\\DTO'                  => ATBDP_INC_DIR . 'dto/subscription/dto.php',
    'Directorist\\Enums\\Order\\DiscountType'              => ATBDP_INC_DIR . 'enums/order/discount-type.php',
    'Directorist\\Enums\\Order\\Status'                    => ATBDP_INC_DIR . 'enums/order/status.php',
    'Directorist\\Enums\\Order\\TaxType'                   => ATBDP_INC_DIR . 'enums/order/tax-type.php',
    'Directorist\\Enums\\Payment\\Status'                  => ATBDP_INC_DIR . 'enums/payment/status.php',
    'Directorist\\Enums\\Refund\\Status'                   => ATBDP_INC_DIR . 'enums/refund/status.php',
    'Directorist\\Repositories\\ListingRepository'         => ATBDP_INC_DIR . 'repositories/listing-repository.php',
    'Directorist\\Repositories\\OrderRepository'           => ATBDP_INC_DIR . 'repositories/order-repository.php',
    'Directorist\\Repositories\\PaymentRepository'         => ATBDP_INC_DIR . 'repositories/payment-repository.php',
    'Directorist\\Repositories\\RefundRepository'          => ATBDP_INC_DIR . 'repositories/refund-repository.php',
    'Directorist\\Repositories\\SubscriptionRepository'    => ATBDP_INC_DIR . 'repositories/subscription-repository.php',
    'Directorist\\database\\DB'                            => ATBDP_INC_DIR . 'database/db.php',
    'Directorist\\database\\Listing_Index'                 => ATBDP_INC_DIR . 'database/class-listing-index.php',
    'Directorist\\database\\Listing_Index_CLI'             => ATBDP_INC_DIR . 'database/class-listing-index-cli.php',
    'Directorist\\database\\Listing_Index_Directory_State' => ATBDP_INC_DIR . 'database/class-listing-index-directory-state.php',
    'Directorist\\database\\Listing_Index_Lifecycle'       => ATBDP_INC_DIR . 'database/class-listing-index-lifecycle.php',
    'Directorist\\database\\Listing_Index_Maintenance'     => ATBDP_INC_DIR . 'database/class-listing-index-maintenance.php',
    'Directorist\\database\\Listing_Index_Query'           => ATBDP_INC_DIR . 'database/class-listing-index-query.php',
    'Directorist\\database\\Listing_Index_Schema'          => ATBDP_INC_DIR . 'database/class-listing-index-schema.php',
    'Directorist\\database\\Listing_Index_Text'            => ATBDP_INC_DIR . 'database/class-listing-index-text.php',
    'ATBDP_Terms_Data_Store'                               => ATBDP_INC_DIR . 'data-store/class-atbdp-terms-store.php',
    'Directorist\\Directorist_Account'                     => ATBDP_INC_DIR . 'model/Account.php',
    'Directorist\\Directorist_All_Authors'                 => ATBDP_INC_DIR . 'model/All_Authors.php',
    'Directorist\\Directorist_Listing_Author'              => ATBDP_INC_DIR . 'model/ListingAuthor.php',
    'Directorist\\Directorist_Listing_Dashboard'           => ATBDP_INC_DIR . 'model/ListingDashboard.php',
    'Directorist\\Directorist_Listing_Form'                => ATBDP_INC_DIR . 'model/ListingForm.php',
    'Directorist\\Directorist_Listing_Search_Form'         => ATBDP_INC_DIR . 'model/SearchForm.php',
    'Directorist\\Directorist_Listing_Taxonomy'            => ATBDP_INC_DIR . 'model/ListingTaxonomy.php',
    'Directorist\\Directorist_Listings'                    => ATBDP_INC_DIR . 'model/Listings.php',
    'Directorist\\Directorist_Single_Listing'              => ATBDP_INC_DIR . 'model/SingleListing.php',
    'ATBDP_Gateway'                                        => ATBDP_INC_DIR . 'gateways/class-gateway.php',
    'ATBDP_Offline_Gateway'                                => ATBDP_INC_DIR . 'gateways/class-offline-gateway.php',
    'ATBDP_Order'                                          => ATBDP_INC_DIR . 'payments/class-order.php',
    'ATBDP_Listings_Data_Store'                            => ATBDP_INC_DIR . 'deprecated/class-atbdp-listing-store.php',
    'Directorist\\Script_Helper'                           => ATBDP_INC_DIR . 'deprecated/class-script-helper.php',
];
